version: '3.9'

services:
  reservationservice:
    build:
      context: ./ReservationService
      dockerfile: Dockerfile
    container_name: reservationservice
    ports:
      - "5001:80"
    depends_on:
      - rabbitmq
      - mssql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=ReservationsDb;User=sa;Password=Your_password123;Encrypt=false;TrustServerCertificate=true;
    restart: unless-stopped

  paymentservice:
    build:
      context: ./PaymentService
      dockerfile: Dockerfile
    container_name: paymentservice
    ports:
      - "5002:80"
    depends_on:
      - rabbitmq
      - mssql
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=ReservationsDb;User=sa;Password=Your_password123;Encrypt=false;TrustServerCertificate=true;
      - Redis__Host=redis

    restart: unless-stopped
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    restart: unless-stopped

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
      - ./sql/init.sql:/tmp/init.sql
    restart: unless-stopped

  initdb:
    image: mcr.microsoft.com/mssql-tools
    container_name: initdb
    depends_on:
      - mssql
    volumes:
      - ./sql/init.sql:/tmp/init.sql
    entrypoint: >
      /bin/bash -c "
      echo 'Waiting for SQL Server...';
      sleep 20;
      /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P Your_password123 -i /tmp/init.sql;
      echo 'Database initialized.'
      "
    restart: "no"

volumes:
  mssqldata:
