version: '3.9'

services:
  reservationservice:
    build:
      context: ./ReservationService
      dockerfile: Dockerfile
    container_name: reservationservice
    ports:
      - "5001:80"
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped

  paymentservice:
    build:
      context: ./PaymentService
      dockerfile: Dockerfile
    container_name: paymentservice
    ports:
      - "5002:80"
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    restart: unless-stopped
